#include <vector>
#include <string>
#include <unordered_map>

enum class TableTokens {
    // Start symbol
    S,

    // Program and declarations
    PROGRAM,
    DECLS_OPT,
    DECLS_LIST_OPT,
    PROC_DECLS_OPT,
    PROC_DECLS_LIST_OPT,
    DECL,
    VAR_DECL,
    VAR_DECL_TYPE_OPT,
    VAR_DECL_EXP_OPT,
    PROC_DECL,
    REC_DECL,

    // Parameter fields
    PARAMFIELD_TYPE_OPT,
    PARAMFIELD_DECL_OPT,
    PARAMFIELD_DECL_LIST,
    PARAMFIELD_DECL_LIST_OPT,
    PARAMFIELD_DECL_OPT_LINE,
    PARAMFIELD_DECL_LIST_LINE,
    PARAMFIELD_DECL_LIST_OPT_LINE,

    // Statements
    STMT_LIST,
    STMT_TAIL,
    STMT,
    IF_STMT,
    IF_ELSE,
    WHILE_STMT,
    RETURN_STMT,
    FOR_STMT,
    DO_UNTIL_STMT,

    // Expressions
    EXP,
    OR_EXP,
    OR_EXP_TAIL,
    AND_EXP,
    AND_EXP_TAIL,
    REL_EXP,
    REL_EXP_TAIL,
    ADD_EXP,
    ADD_EXP_TAIL,
    MUL_EXP,
    MUL_EXP_TAIL,
    POW_EXP,
    POW_EXP_TAIL,
    UNARY_EXP,
    PRIMARY,

    // Expression helpers
    MAYBE_ACESS_TAIL,
    CALL_OR_ASSIGNMET,
    ACCESS_TAIL,
    REF_VAR,
    DEREF_VAR,
    MAYBE_CALL,
    EXP_LIST,
    EXP_TAIL,
    LITERAL,

    // Terminals / pseudo-terminals
    EMPTY,
    SEMICOLON,
    ATTRIBUTION,
    OPENPARENTHESES,
    CLOSEPARENTHESES,
    OPENBRACKETS,
    CLOSEBRACKETS,
    COLON,
    COMMA,
    DOT,

    // Operators
    SUMINUS,
    MULDIV,
    REL_OP,
    OR,
    AND,
    NOT,
    EQUALS,
    DIFFERENTTHAN,
    LESSTHAN,
    LESSTHANEQUALS,
    GREATERTHAN,
    GREATERTHANEQUALS,
    PLUS,
    MINUS,
    MULT,
    DIV,
    POW,
    IN,

    // Keywords
    VAR,
    TYPE,
    PROCEDURE,
    STRUCT,
    BEGIN,
    END,
    IF,
    THEN,
    ELSE,
    FI,
    WHILE,
    DO,
    UNTIL,
    RETURN,
    FOR,
    STEP,
    TO,
    OD,

    // Types and literals
    FLOAT,
    INT,
    STRING,
    BOOL,
    FLOAT_literal,
    INT_literal,
    STRING_literal,
    BOOL_literal,
    NULL_,

    // Special symbols
    REF,
    DEREF,
    NEW,
    DOLAR,
    NAME
};

// {{}, "$", "program", "name", "begin", "end", ";", "in", "var", ":", ":=", "procedure", "(", ")", ",", "struct", "{", "}", "||", "&&", "^", "not", "new", ".", "ref", "deref", "+", "-", "*", "/", "<", "<=", ">", ">=", "=", "<>", "float_literal", "int_literal", "string_literal", "bool_literal", "null", "if", "then", "fi", "else", "while", "do", "od", "return", "float", "int", "string", "bool", "for", "to", "step", "until"},

std::unordered_map<std::string, TableTokens> tokenMap = {
    {"$", TableTokens::DOLAR},
    {"program", TableTokens::PROGRAM},
    {"name", TableTokens::NAME},
    {"begin", TableTokens::BEGIN},
    {"end", TableTokens::END},
    {";", TableTokens::SEMICOLON},
    {"in", TableTokens::IN},
    {"var", TableTokens::VAR},
    {":", TableTokens::COLON},
    {":=", TableTokens::ATTRIBUTION},
    {"procedure", TableTokens::PROCEDURE},
    {"(", TableTokens::OPENPARENTHESES},
    {")", TableTokens::CLOSEPARENTHESES},
    {",", TableTokens::COMMA},
    {"struct", TableTokens::STRUCT},
    {"{", TableTokens::OPENBRACKETS},
    {"}", TableTokens::CLOSEBRACKETS},
    {"||", TableTokens::OR},
    {"&&", TableTokens::AND},
    {"^", TableTokens::POW},
    {"not", TableTokens::NOT},
    {"new", TableTokens::NEW},
    {".", TableTokens::DOT},
    {"ref", TableTokens::REF},
    {"deref", TableTokens::DEREF},
    {"+", TableTokens::PLUS},
    {"-", TableTokens::MINUS},
    {"*", TableTokens::MULT},
    {"/", TableTokens::DIV},
    {"<", TableTokens::LESSTHAN},
    {"<=", TableTokens::LESSTHANEQUALS},
    {">", TableTokens::GREATERTHAN},
    {">=", TableTokens::GREATERTHANEQUALS},
    {"=", TableTokens::EQUALS},
    {"<>", TableTokens::DIFFERENTTHAN},
    {"float_literal", TableTokens::FLOAT_literal},
    {"int_literal", TableTokens::INT_literal},
    {"string_literal", TableTokens::STRING_literal},
    {"bool_literal", TableTokens::BOOL_literal},
    {"NULL_", TableTokens::NULL_},
    {"if", TableTokens::IF},
    {"then", TableTokens::THEN},
    {"fi", TableTokens::FI},
    {"else", TableTokens::ELSE},
    {"while", TableTokens::WHILE},
    {"do", TableTokens::DO},
    {"od", TableTokens::OD},
    {"return", TableTokens::RETURN},
    {"float", TableTokens::FLOAT},
    {"int", TableTokens::INT},
    {"string", TableTokens::STRING},
    {"bool", TableTokens::BOOL},
    {"for", TableTokens::FOR},
    {"to", TableTokens::TO},
    {"step", TableTokens::STEP},
    {"until", TableTokens::UNTIL}
};

std::vector<std::vector<std::vector<TableTokens>>> table = {
    {{TableTokens::S}, {}, {TableTokens::PROGRAM, TableTokens::DOLAR}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PROGRAM}, {}, {TableTokens::PROGRAM, TableTokens::NAME, TableTokens::BEGIN, TableTokens::DECLS_OPT, TableTokens::END}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::DECLS_OPT}, {}, {}, {}, {}, {TableTokens::EMPTY}, {}, {}, {TableTokens::DECL, TableTokens::DECLS_LIST_OPT}, {}, {}, {TableTokens::DECL, TableTokens::DECLS_LIST_OPT}, {}, {}, {}, {TableTokens::DECL, TableTokens::DECLS_LIST_OPT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::DECLS_LIST_OPT}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::SEMICOLON, TableTokens::DECL, TableTokens::DECLS_LIST_OPT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PROC_DECLS_OPT}, {}, {}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {}, {}, {TableTokens::DECL, TableTokens::PROC_DECLS_LIST_OPT, TableTokens::IN}, {}, {}, {TableTokens::DECL, TableTokens::PROC_DECLS_LIST_OPT, TableTokens::IN}, {TableTokens::EMPTY}, {}, {}, {TableTokens::DECL, TableTokens::PROC_DECLS_LIST_OPT, TableTokens::IN}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {}, {}, {}, {}, {TableTokens::EMPTY}, {}, {}, {}},
    {{TableTokens::PROC_DECLS_LIST_OPT}, {}, {}, {}, {}, {}, {TableTokens::SEMICOLON, TableTokens::DECL, TableTokens::PROC_DECLS_LIST_OPT}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::DECL}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::VAR_DECL}, {}, {}, {TableTokens::PROC_DECL}, {}, {}, {}, {TableTokens::REC_DECL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::VAR_DECL}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::VAR, TableTokens::NAME, TableTokens::VAR_DECL_TYPE_OPT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::VAR_DECL_TYPE_OPT}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::COLON, TableTokens::TYPE, TableTokens::VAR_DECL_EXP_OPT}, {TableTokens::ATTRIBUTION, TableTokens::EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::VAR_DECL_EXP_OPT}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {TableTokens::ATTRIBUTION, TableTokens::EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PROC_DECL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::PROCEDURE, TableTokens::NAME, TableTokens::OPENPARENTHESES, TableTokens::PARAMFIELD_DECL_OPT, TableTokens::CLOSEPARENTHESES, TableTokens::PARAMFIELD_TYPE_OPT, TableTokens::BEGIN, TableTokens::PROC_DECLS_OPT, TableTokens::STMT_LIST, TableTokens::END}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PARAMFIELD_TYPE_OPT}, {}, {}, {}, {TableTokens::EMPTY}, {}, {}, {}, {}, {TableTokens::COLON, TableTokens::TYPE}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PARAMFIELD_DECL_OPT}, {}, {}, {TableTokens::PARAMFIELD_DECL_LIST}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PARAMFIELD_DECL_LIST}, {}, {}, {TableTokens::NAME, TableTokens::COLON, TableTokens::TYPE, TableTokens::PARAMFIELD_DECL_LIST_OPT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PARAMFIELD_DECL_LIST_OPT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::COMMA, TableTokens::PARAMFIELD_DECL_LIST}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::REC_DECL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::STRUCT, TableTokens::NAME, TableTokens::OPENBRACKETS, TableTokens::PARAMFIELD_DECL_OPT_LINE, TableTokens::CLOSEBRACKETS}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PARAMFIELD_DECL_OPT_LINE}, {}, {}, {TableTokens::PARAMFIELD_DECL_LIST_LINE}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PARAMFIELD_DECL_LIST_LINE}, {}, {}, {TableTokens::NAME, TableTokens::COLON, TableTokens::TYPE, TableTokens::PARAMFIELD_DECL_LIST_OPT_LINE}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PARAMFIELD_DECL_LIST_OPT_LINE}, {}, {}, {}, {}, {}, {TableTokens::SEMICOLON, TableTokens::PARAMFIELD_DECL_LIST_LINE}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::STMT_LIST}, {}, {}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {TableTokens::EMPTY}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {}, {}, {}, {}, {TableTokens::STMT, TableTokens::STMT_TAIL}, {}, {}, {TableTokens::EMPTY}},
    {{TableTokens::STMT_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::SEMICOLON, TableTokens::STMT_LIST}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}},
    {{TableTokens::EXP}, {}, {}, {TableTokens::OR_EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::OR_EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::OR_EXP}, {TableTokens::OR_EXP}, {}, {TableTokens::OR_EXP}, {TableTokens::OR_EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::OR_EXP}, {TableTokens::OR_EXP}, {TableTokens::OR_EXP}, {TableTokens::OR_EXP}, {TableTokens::OR_EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::OR_EXP}, {}, {}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::OR_EXP_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::OR, TableTokens::AND_EXP, TableTokens::OR_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}},
    {{TableTokens::AND_EXP}, {}, {}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::AND_EXP_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::AND, TableTokens::REL_EXP, TableTokens::AND_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}},
    {{TableTokens::REL_EXP}, {}, {}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::REL_EXP_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::REL_OP, TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::REL_OP, TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::REL_OP, TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::REL_OP, TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::REL_OP, TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {TableTokens::REL_OP, TableTokens::ADD_EXP, TableTokens::REL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}},
    {{TableTokens::ADD_EXP}, {}, {}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::ADD_EXP_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::SUMINUS, TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {TableTokens::SUMINUS, TableTokens::MUL_EXP, TableTokens::ADD_EXP_TAIL}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}},
    {{TableTokens::MUL_EXP}, {}, {}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::MUL_EXP_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::MULDIV, TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {TableTokens::MULDIV, TableTokens::POW_EXP, TableTokens::MUL_EXP_TAIL}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}},
    {{TableTokens::POW_EXP}, {}, {}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::POW_EXP_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::POW, TableTokens::UNARY_EXP, TableTokens::POW_EXP_TAIL}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}},
    {{TableTokens::UNARY_EXP}, {}, {}, {TableTokens::PRIMARY}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::PRIMARY}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::NOT, TableTokens::UNARY_EXP}, {TableTokens::PRIMARY}, {}, {TableTokens::PRIMARY}, {TableTokens::PRIMARY}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::PRIMARY}, {TableTokens::PRIMARY}, {TableTokens::PRIMARY}, {TableTokens::PRIMARY}, {TableTokens::PRIMARY}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::MAYBE_ACESS_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}},
    {{TableTokens::CALL_OR_ASSIGNMET}, {}, {}, {TableTokens::NAME, TableTokens::MAYBE_CALL, TableTokens::MAYBE_ACESS_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::OPENPARENTHESES, TableTokens::EXP, TableTokens::CLOSEPARENTHESES, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::NEW, TableTokens::NAME, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {}, {TableTokens::REF_VAR, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {TableTokens::DEREF_VAR, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL, TableTokens::ATTRIBUTION, TableTokens::EXP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::PRIMARY}, {}, {}, {TableTokens::NAME, TableTokens::MAYBE_CALL, TableTokens::ACCESS_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::OPENPARENTHESES, TableTokens::EXP, TableTokens::CLOSEPARENTHESES, TableTokens::ACCESS_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::NEW, TableTokens::NAME, TableTokens::ACCESS_TAIL}, {}, {TableTokens::REF_VAR, TableTokens::ACCESS_TAIL}, {TableTokens::DEREF_VAR, TableTokens::ACCESS_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL}, {TableTokens::LITERAL, TableTokens::ACCESS_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::ACCESS_TAIL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {TableTokens::EMPTY}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {TableTokens::DOT, TableTokens::NAME, TableTokens::ACCESS_TAIL}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}},
    {{TableTokens::REF_VAR}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::REF, TableTokens::OPENPARENTHESES, TableTokens::PRIMARY, TableTokens::CLOSEPARENTHESES}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::DEREF_VAR}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::DEREF, TableTokens::OPENPARENTHESES, TableTokens::PRIMARY, TableTokens::CLOSEPARENTHESES}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::MAYBE_CALL}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {TableTokens::EMPTY}, {}, {TableTokens::OPENPARENTHESES, TableTokens::EXP_LIST, TableTokens::CLOSEPARENTHESES}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {TableTokens::EMPTY}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::EMPTY}, {TableTokens::EMPTY}},
    {{TableTokens::EXP_LIST}, {}, {}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {TableTokens::EMPTY}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {TableTokens::EXP, TableTokens::EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::COMMA, TableTokens::EXP, TableTokens::EXP_TAIL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::SUMINUS}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::PLUS}, {TableTokens::MINUS}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::MULDIV}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::MULT}, {TableTokens::DIV}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::REL_OP}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::LESSTHAN}, {TableTokens::LESSTHANEQUALS}, {TableTokens::GREATERTHAN}, {TableTokens::GREATERTHANEQUALS}, {TableTokens::EQUALS}, {TableTokens::DIFFERENTTHAN}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::LITERAL}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::FLOAT_literal}, {TableTokens::INT_literal}, {TableTokens::STRING_literal}, {TableTokens::BOOL_literal}, {TableTokens::NULL_}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::STMT}, {}, {}, {TableTokens::CALL_OR_ASSIGNMET}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::CALL_OR_ASSIGNMET}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::CALL_OR_ASSIGNMET}, {}, {TableTokens::CALL_OR_ASSIGNMET}, {TableTokens::CALL_OR_ASSIGNMET}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::CALL_OR_ASSIGNMET}, {TableTokens::CALL_OR_ASSIGNMET}, {TableTokens::CALL_OR_ASSIGNMET}, {TableTokens::CALL_OR_ASSIGNMET}, {TableTokens::CALL_OR_ASSIGNMET}, {TableTokens::IF_STMT}, {}, {}, {}, {TableTokens::WHILE_STMT}, {TableTokens::DO_UNTIL_STMT}, {}, {TableTokens::RETURN_STMT}, {}, {}, {}, {}, {TableTokens::FOR_STMT}, {}, {}, {}},
    {{TableTokens::IF_STMT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::IF, TableTokens::EXP, TableTokens::THEN, TableTokens::STMT_LIST, TableTokens::IF_ELSE, TableTokens::FI}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::IF_ELSE}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::EMPTY}, {TableTokens::ELSE, TableTokens::STMT_LIST}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::WHILE_STMT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::WHILE, TableTokens::EXP, TableTokens::DO, TableTokens::STMT_LIST, TableTokens::OD}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::RETURN_STMT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::RETURN, TableTokens::OPENPARENTHESES, TableTokens::EXP, TableTokens::CLOSEPARENTHESES}, {}, {}, {}, {}, {}, {}, {}, {}},
    {{TableTokens::TYPE}, {}, {}, {TableTokens::NAME}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::REF, TableTokens::OPENPARENTHESES, TableTokens::TYPE, TableTokens::CLOSEPARENTHESES}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::FLOAT}, {TableTokens::INT}, {TableTokens::STRING}, {TableTokens::BOOL}, {}, {}, {}, {}},
    {{TableTokens::FOR_STMT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::FOR, TableTokens::PRIMARY, TableTokens::EQUALS, TableTokens::EXP, TableTokens::TO, TableTokens::EXP, TableTokens::STEP, TableTokens::EXP, TableTokens::DO, TableTokens::STMT_LIST, TableTokens::OD}, {}, {}, {}},
    {{TableTokens::DO_UNTIL_STMT}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {TableTokens::DO, TableTokens::STMT_LIST, TableTokens::UNTIL, TableTokens::EXP, TableTokens::OD}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}},
};