#!/bin/bash

# Constants
FOLDER="./examples"

if [ "$1"  = "recursive" ]; then
   SCRIPT="./build/recursive_parser"
elif [ "$1" = "table" ]; then
   SCRIPT="./build/table_parser"
else
   echo "Usage: test {recursive|table}"
   exit 1
fi

echo "Running $1 parser..."
# Loop through each file in the folder
for FILE in "$FOLDER"/*; do
  if [ -f "$FILE" ]; then
    ("$SCRIPT" < "$FILE") > 'tmp.txt'
    EXIT_CODE=$?
    if [ $EXIT_CODE -eq 1 ]; then
      echo "[TEST] $FILE : Detected error"
      CONTENT="$(</tmp/compiler_results.txt)"
      echo "[MESSAGE] $CONTENT"
    else 
      echo "[TEST] $FILE : Success"
    fi
  fi
done